# Generated by Django 3.1.4 on 2021-02-01 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('free_or_paid', models.CharField(blank=True, choices=[('P', 'Paid'), ('F', 'Free')], max_length=1)),
                ('rate', models.IntegerField(default=0)),
                ('text', models.TextField(blank=True)),
                ('instructor_rate', models.IntegerField(default=0)),
                ('pace_rate', models.IntegerField(default=0)),
                ('depth_coverage_rate', models.IntegerField(default=0)),
                ('quality_rate', models.IntegerField(default=0)),
                ('number_of_comments', models.PositiveIntegerField(default=0)),
                ('number_of_views', models.PositiveIntegerField(default=0)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('have_book', models.BooleanField(default=False)),
                ('have_site', models.BooleanField(default=False)),
                ('have_video', models.BooleanField(default=False)),
                ('have_excersice', models.BooleanField(default=False)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='courses.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.comment')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
